window.embeddedUITexts = {
  de: {
    uiLangLabel: "Oberfläche:",
    labelLang: "Sprache",
    labelVoice: "Stimme",
    labelDigitLength: "Ziffernlänge",
    labelCount: "Anzahl",
    labelRepeat: "Wiederholen",
    labelSpeed: "Tempo",
    labelDelay: "Pause",
    fillRandom: "🎲 Rnd",
    start: "Start",
    continue: "Fortsetzen",
    pause: "Pause",
    reset: "Zurücksetzen",
    repeatsLeft: "Wiederholungen übrig:",
    default: "Standard",
    labelFullscreen: "Vollbild",
    fullscreenNo: "Nein",
    fullscreenYes: "Ja",
  },
  en: {
    uiLangLabel: "Interface:",
    labelLang: "Language",
    labelVoice: "Voice",
    labelDigitLength: "Digit length",
    labelCount: "Count",
    labelRepeat: "Repeat",
    labelSpeed: "Speed",
    labelDelay: "Delay",
    fillRandom: "🎲 Rnd",
    start: "Start",
    continue: "Continue",
    pause: "Pause",
    reset: "Reset",
    repeatsLeft: "Repeats left:",
    default: "Default",
    labelFullscreen: "Fullscreen",
    fullscreenNo: "No",
    fullscreenYes: "Yes",
  },
  fr: {
    uiLangLabel: "Interface :",
    labelLang: "Langue",
    labelVoice: "Voix",
    labelDigitLength: "Longueur",
    labelCount: "Nombre",
    labelRepeat: "Répét.",
    labelSpeed: "Vitesse",
    labelDelay: "Pause",
    fillRandom: "🎲 Rnd",
    start: "Démarrer",
    continue: "Continuer",
    pause: "Pause",
    reset: "Réinitialiser",
    repeatsLeft: "Répétitions :",
    default: "Défaut",
    labelFullscreen: "Plein écran",
    fullscreenNo: "Non",
    fullscreenYes: "Oui",
  },
  nl: {
    uiLangLabel: "Interface:",
    labelLang: "Taal",
    labelVoice: "Stem",
    labelDigitLength: "Lengte",
    labelCount: "Aantal",
    labelRepeat: "Herhaal",
    labelSpeed: "Snelheid",
    labelDelay: "Pauze",
    fillRandom: "🎲 Rnd",
    start: "Start",
    continue: "Doorgaan",
    pause: "Pauze",
    reset: "Opnieuw",
    repeatsLeft: "Herhalingen:",
    default: "Standaard",
    labelFullscreen: "Volledig scherm",
    fullscreenNo: "Nee",
    fullscreenYes: "Ja",
  },
  pl: {
    uiLangLabel: "Interfejs:",
    labelLang: "Język",
    labelVoice: "Głos",
    labelDigitLength: "Długość",
    labelCount: "Ilość",
    labelRepeat: "Powtórz",
    labelSpeed: "Tempo",
    labelDelay: "Pauza",
    fillRandom: "🎲 Rnd",
    start: "Start",
    continue: "Kontynuuj",
    pause: "Pauza",
    reset: "Resetuj",
    repeatsLeft: "Pozostało:",
    default: "Domyślne",
    labelFullscreen: "Pełny ekran",
    fullscreenNo: "Nie",
    fullscreenYes: "Tak",
  },
  pt: {
    uiLangLabel: "Interface:",
    labelLang: "Idioma",
    labelVoice: "Voz",
    labelDigitLength: "Dígitos",
    labelCount: "Qtd",
    labelRepeat: "Repetir",
    labelSpeed: "Veloc.",
    labelDelay: "Pausa",
    fillRandom: "🎲 Rnd",
    start: "Iniciar",
    continue: "Continuar",
    pause: "Pausar",
    reset: "Resetar",
    repeatsLeft: "Restantes:",
    default: "Padrão",
    labelFullscreen: "Tela cheia",
    fullscreenNo: "Não",
    fullscreenYes: "Sim",
  },
  ru: {
    uiLangLabel: "Интерфейс:",
    labelLang: "Язык",
    labelVoice: "Голос",
    labelDigitLength: "Длина",
    labelCount: "Кол-во",
    labelRepeat: "Повтор",
    labelSpeed: "Темп",
    labelDelay: "Пауза",
    fillRandom: "🎲 Rnd",
    start: "Старт",
    continue: "Продолжить",
    pause: "Пауза",
    reset: "Сброс",
    repeatsLeft: "Осталось:",
    default: "По умолчанию",
    labelFullscreen: "Полный экран",
    fullscreenNo: "Нет",
    fullscreenYes: "Да",
  },
  tr: {
    uiLangLabel: "Arayüz:",
    labelLang: "Dil",
    labelVoice: "Ses",
    labelDigitLength: "Basamak",
    labelCount: "Sayı",
    labelRepeat: "Tekrar",
    labelSpeed: "Hız",
    labelDelay: "Ara",
    fillRandom: "🎲 Rnd",
    start: "Başlat",
    continue: "Sürdür",
    pause: "Duraklat",
    reset: "Sıfırla",
    repeatsLeft: "Kaldı:",
    default: "Varsayılan",
    labelFullscreen: "Tam ekran",
    fullscreenNo: "Hayır",
    fullscreenYes: "Evet",
  },
  uk: {
    uiLangLabel: "Інтерфейс:",
    labelLang: "Мова",
    labelVoice: "Голос",
    labelDigitLength: "Довжина",
    labelCount: "Кількість",
    labelRepeat: "Повтор",
    labelSpeed: "Темп",
    labelDelay: "Пауза",
    fillRandom: "🎲 Rnd",
    start: "Почати",
    continue: "Продовжити",
    pause: "Пауза",
    reset: "Скинути",
    repeatsLeft: "Залишилось:",
    default: "Типові",
    labelFullscreen: "Повний екран",
    fullscreenNo: "Ні",
    fullscreenYes: "Так",
  },
};
