window.embeddedUITexts = {
  de: {
    uiLangLabel: "Oberfläche",
    labelLang: "Sprache",
    labelVoice: "Stimme",
    labelDigitLength: "Ziffernlänge",
    labelCount: "Anzahl",
    labelRepeat: "Wiederholen",
    labelSpeed: "Tempo",
    labelDelay: "Pause",
    labelFullscreen: "Vollbild",
    start: "Start",
    continue: "Weiter",
    pause: "Pause",
    reset: "Zurücksetzen",
    fillRandom: "🎲 Zufall",
    fullscreenNo: "Nein",
    fullscreenYes: "Ja",
    default: "Standard",
    repeatsLeft: "Wiederholungen übrig:",
  },
  en: {
    uiLangLabel: "Interface",
    labelLang: "Language",
    labelVoice: "Voice",
    labelDigitLength: "Digit length",
    labelCount: "Count",
    labelRepeat: "Repeat",
    labelSpeed: "Speed",
    labelDelay: "Delay",
    labelFullscreen: "Fullscreen",
    start: "Start",
    continue: "Continue",
    pause: "Pause",
    reset: "Reset",
    fillRandom: "🎲 Random",
    fullscreenNo: "No",
    fullscreenYes: "Yes",
    default: "Default",
    repeatsLeft: "Repeats left:",
  },
  fr: {
    uiLangLabel: "Interface",
    labelLang: "Langue",
    labelVoice: "Voix",
    labelDigitLength: "Longueur",
    labelCount: "Nombre",
    labelRepeat: "Répéter",
    labelSpeed: "Vitesse",
    labelDelay: "Pause",
    labelFullscreen: "Plein écran",
    start: "Démarrer",
    continue: "Continuer",
    pause: "Pause",
    reset: "Réinitialiser",
    fillRandom: "🎲 Aléatoire",
    fullscreenNo: "Non",
    fullscreenYes: "Oui",
    default: "Par défaut",
    repeatsLeft: "Répétitions restantes:",
  },
  nl: {
    uiLangLabel: "Interface",
    labelLang: "Taal",
    labelVoice: "Stem",
    labelDigitLength: "Lengte",
    labelCount: "Aantal",
    labelRepeat: "Herhalen",
    labelSpeed: "Snelheid",
    labelDelay: "Pauze",
    labelFullscreen: "Volledig scherm",
    start: "Start",
    continue: "Doorgaan",
    pause: "Pauze",
    reset: "Opnieuw instellen",
    fillRandom: "🎲 Willekeurig",
    fullscreenNo: "Nee",
    fullscreenYes: "Ja",
    default: "Standaard",
    repeatsLeft: "Herhalingen over:",
  },
  pl: {
    uiLangLabel: "Interfejs",
    labelLang: "Język",
    labelVoice: "Głos",
    labelDigitLength: "Długość",
    labelCount: "Ilość",
    labelRepeat: "Powtórzenie",
    labelSpeed: "Tempo",
    labelDelay: "Pauza",
    labelFullscreen: "Pełny ekran",
    start: "Start",
    continue: "Kontynuuj",
    pause: "Pauza",
    reset: "Resetuj",
    fillRandom: "🎲 Losowy",
    fullscreenNo: "Nie",
    fullscreenYes: "Tak",
    default: "Domyślne",
    repeatsLeft: "Pozostało:",
  },
  pt: {
    uiLangLabel: "Interface",
    labelLang: "Idioma",
    labelVoice: "Voz",
    labelDigitLength: "Dígitos",
    labelCount: "Quantidade",
    labelRepeat: "Repetir",
    labelSpeed: "Velocidade",
    labelDelay: "Pausa",
    labelFullscreen: "Tela cheia",
    start: "Iniciar",
    continue: "Continuar",
    pause: "Pausar",
    reset: "Redefinir",
    fillRandom: "🎲 Aleatório",
    fullscreenNo: "Não",
    fullscreenYes: "Sim",
    default: "Padrão",
    repeatsLeft: "Restantes:",
  },
  ru: {
    uiLangLabel: "Интерфейс",
    labelLang: "Язык",
    labelVoice: "Голос",
    labelDigitLength: "Длина",
    labelCount: "Количество",
    labelRepeat: "Повтор",
    labelSpeed: "Темп",
    labelDelay: "Пауза",
    labelFullscreen: "Полный экран",
    start: "Старт",
    continue: "Продолжить",
    pause: "Пауза",
    reset: "Сброс",
    fillRandom: "🎲 Случайно",
    fullscreenNo: "Нет",
    fullscreenYes: "Да",
    default: "По умолчанию",
    repeatsLeft: "Осталось:",
  },
  tr: {
    uiLangLabel: "Arayüz",
    labelLang: "Dil",
    labelVoice: "Ses",
    labelDigitLength: "Basamak",
    labelCount: "Sayı",
    labelRepeat: "Tekrar",
    labelSpeed: "Hız",
    labelDelay: "Ara",
    labelFullscreen: "Tam ekran",
    start: "Başlat",
    continue: "Devam et",
    pause: "Duraklat",
    reset: "Sıfırla",
    fillRandom: "🎲 Rastgele",
    fullscreenNo: "Hayır",
    fullscreenYes: "Evet",
    default: "Varsayılan",
    repeatsLeft: "Kaldı:",
  },
  uk: {
    uiLangLabel: "Інтерфейс",
    labelLang: "Мова",
    labelVoice: "Голос",
    labelDigitLength: "Довжина",
    labelCount: "Кількість",
    labelRepeat: "Повтор",
    labelSpeed: "Темп",
    labelDelay: "Пауза",
    labelFullscreen: "Повний екран",
    start: "Почати",
    continue: "Продовжити",
    pause: "Пауза",
    reset: "Скинути",
    fillRandom: "🎲 Випадково",
    fullscreenNo: "Ні",
    fullscreenYes: "Так",
    default: "Типові",
    repeatsLeft: "Залишилось:",
  },
};
